#version: "3.9"
#services:
#  web:
#    build:
#      context: ./
#      dockerfile: Dockerfile

#    ports:
#      - "4200:4200"




version: "3.9"
services:
  web:
    build: .
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - "4200:4200"